.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. koobit_qt test_koobit_qt
clean: FORCE
	$(MAKE) -C .. koobit_qt_clean test_koobit_qt_clean
check: FORCE
	$(MAKE) -C .. test_koobit_qt_check
koobit-qt koobit-qt.exe: FORCE
	 $(MAKE) -C .. koobit_qt
